apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: hpa
        image: k8s.gcr.io/hpa-example
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
